# Use official Tomcat image with Java 17
FROM tomcat:9.0-jdk17-temurin

# Remove the default webapps to deploy your own
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy the WAR file generated by Maven
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war

# Expose Tomcat default port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
